export const FLAGS = {
  FEATURE_HOME_QUICK_ACTIONS: true,
  FEATURE_HOME_PARTNERS_SECTION: true,
  FEATURE_HOME_DONATE_SECTION: true,
  FEATURE_DEVOTIONAL_V1: true,
  FEATURE_PRAYER_REQUESTS_V1: true,
};
