export const FLAGS = {
  FEATURE_HOME_QUICK_ACTIONS: true,
  FEATURE_HOME_PARTNERS_SECTION: true,
  FEATURE_HOME_DONATE_SECTION: true,
  FEATURE_DEVOTIONAL_V1: true,
  FEATURE_PRAYER_REQUESTS_V1: true,
  // Sprint 3: API Integration
  FEATURE_DEVOTIONAL_API: true,
  FEATURE_PRAYER_API: true,
  // Sprint X: Monetization
  FEATURE_DEVOTIONAL_SUPPORT_BLOCK: true,
  FEATURE_DEVOTIONAL_SPONSOR_HIGHLIGHT: true,
  FEATURE_SUPPORT_FOOTER: true,
  FEATURE_HOME_RETURN_PILL: true,
};
